### ISSUE TITLE
Rewrite vue-video-player in typescript

### ISSUE THREAD

**Issue by qdot** [metafetish/syncydink#6]
The vue-video-player is a fairly simple wrapper around video.js, that works ok enough. However, it lacks type symbols, some of the font loading doesn't seem to play well with our type system, etc. It should be fairly easy to reimplement it in typescript, and gives us more flexibility in working with video.js, since we may be doing odd stuff with it.

**Comment by amelzer** [comment]
Unpopular opinion: ditch the type system :P

**Comment by qdot** [comment]
Ok, update on this:

- The type system wasn't the problem, my lack of understanding of how to work around the type system when using non-typescript libraries was.
- The fonts weren't a problem, my lack of understand of how webpack worked was.

So, types and fonts are figured out. However, this still leaves a much larger issue: this package is missing some events and features of video.js, which would be quite useful for us. Not only that, since we're now using Video.js to control both 2d and VR video, we may want our own hooks closer to the video.js library.

**Comment by amelzer** [comment]
If you have time, could you add a list of things that are missing in your opinion?

**Comment by qdot** [comment]
No longer required. Another 10 months of typescript and vue experience have gotten me what I needed without reinventing wheels.
